# Generated by Django 4.0.3 on 2022-03-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_art_img_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
